version: "3.8"

services:
  srapper_app:
    container_name: web_srapper_app
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    volumes:
      - .:/app
