version: "3"

services:
  srapper_app:
    container_name: web_srapper_app
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://<username>:<password>@<host>:<port>/<database_name>
    volumes:
      - .:/app
